//****************************************Local Host*************************************//

### Test GET request locally
GET http://localhost:3000


### Get all contacts
GET http://localhost:3000/contacts


### Get contact by id
GET http://localhost:3000/contacts/69023d7681987bcaec5241d5


### Post request, to create a new contact
POST http://localhost:3000/contacts
content-type: application/json


{
    "firstName": "mary",
    "lastName": "maribao",
    "email": "test@gmail.com",
    "favoriteColor": "blue",
    "birthday": "03/15/2001"    
}

### Put request, to update an existing contact
PUT http://localhost:3000/contacts/69023df581987bcaec5241d6
content-type: application/json


{
    "firstName": "Ebuka",
    "lastName": "Okubalu",
    "email": "ebukatest4@gmail.com",
    "favoriteColor": "brown",
    "birthday": "07/14/2003"
}

### Delete request, to delete an existing contact by id
DELETE http://localhost:3000/contacts/690bd8b5a9dbf5783685b462


//**********************Render Environment**************************//

### Test GET request in production
GET https://project1-mvic.onrender.com/

### GET all contacts
GET https://project1-mvic.onrender.com/contacts


### GET contact by id
GET https://project1-mvic.onrender.com/contacts/69023c7681987bcaec5241d4


### Post request, to create a new contact
POST http://project1-mvic.onrender.com/contacts
content-type: application/json


{
    "firstName": "mary",
    "lastName": "maribao",
    "email": "test@gmail.com",
    "favoriteColor": "blue",
    "birthday": "03/15/2001"    
}

### Put request, to update an existing contact
PUT http://project1-mvic.onrender.com/contacts/690bd5fca9dbf5783685b461
content-type: application/json


{
    "firstName": "Ebuka",
    "lastName": "Okubalu",
    "email": "ebukatest4@gmail.com",
    "favoriteColor": "brown",
    "birthday": "07/14/2003"
}

### Delete request, to delete an existing contact by id
DELETE http://project1-mvic.onrender.com/contacts/690be474548003d720d16214

